### PR TITLE
feat(users): Ability to allow login only for approved users 

### PR DESCRIPTION
**Pull request by koriaf**
any user logged in gets database row created
then you approve it
if we don't care about the scenario when we have multiple IDP (like google and facebook at the same time) we may pre-invite users for their email as described in the task (or implement fullscale workflow with invitation links and so on, might not be useful yet)
@monkeypants @simra 
#47

### CODE REVIEW

**Comment by simra** [comment]
This probably works for the time being. 
Creating a row for every random user that signs in might be an issue later- say we have some splashy press coverage and 10000 users sign in and leave a row for us to approve. It might be better to separate these requests into another table, but maybe it's no big issue.
What's the workflow for approval? will we need app UI for that or could we do it via a shell script?

**Comment by koriaf** [comment]
The simplest approval way I see is to add API endpoint to list users, insert new users (filling only their emails) and change flags for existing users (is_active, is_superuser). Swagger will generate the UI and it's easy to use then. These endpoints will be available only to existing superusers, first ones are created based on that hardcoded hack (I guess we may just move list of very trusted emails to ENV variable instead of hardcoding it)

Good point about not creating new records in the users tab automatically, will try to implement something like that right now in this PR

**Comment by koriaf** [comment]
Changed the workflow a bit so users table is not bloated too much but superusers are still can login (note: must configure that env variable on each real setup now)

next step is to create quick API endpoints so superusers can add emails to the users table manually so they can login later

**Review by simra — APPROVED** [review]
looks good, thanks!

**Pull request merged**
