### PR TITLE
Sqlalchemy, update requirements so container builds and so on

### PR DESCRIPTION
**Pull request by koriaf**
@monkeypants  @simra 
I wasn't much successful with the full flow yet but at least it starts, runs migrations, I can more or less import some images and that's all
there is more work to do

https://github.com/Tech4Tracing/CartridgeOCR/issues/21

### CODE REVIEW

**Comment by monkeypants** [comment]
Tip to new players: `touch src/annotations/.env` (or better still `cp  src/annotations/.env-example  src/annotations/.env`). For README...

**Review by monkeypants — APPROVED** [review]
Nice little cleanup Arkadiy, everything looks sensible.

It builds and runs for me. I didn't test it thoroughly (we really should get some CI testing on this thing)

**Comment by koriaf** [comment]
Screenshot from 2022-03-10 11-36-53

**Comment by koriaf** [comment]
Screenshot from 2022-03-10 19-16-05
Screenshot from 2022-03-10 19-16-14

**Pull request merged**
